#    COPYRIGHT (C) 2024 Mitsubishi Electric Corporation

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    Contributor(s):
#       Liu Muyao

# This is a sample message for MELFA safety_io. All MELFA robots have the same number of pairs of dedicted safety inputs.

bool dsi_1
bool dsi_2
bool dsi_3
bool dsi_4
bool dsi_5
bool dsi_6
bool dsi_7
bool dsi_8
