#    COPYRIGHT (C) 2024 Mitsubishi Electric Corporation

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#    Contributor(s):
#       Liu Muyao

# This is a sample message that maps PLC inputs to a sensor boolean variable.

bool sensor_0
bool sensor_1
bool sensor_2
bool sensor_3
bool sensor_4
bool sensor_5
bool sensor_6
bool sensor_7


